name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Testes Unitários, Integração, Infraestrutura (Jest) e Build
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./backend

    steps:
      - uses: actions/checkout@v4

      - name: Configurar Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Instalar dependências do backend
        run: npm install

      - name: Rodar Testes Jest
        run: npm test

  performance-tests: 
    name: Teste de Performance (k6)
    needs: test 
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./backend

    steps:
      - uses: actions/checkout@v4
      
      - name: Configurar Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Instalar k6 no Runner
        run: |
          sudo apt-get update
          sudo apt-get install -y k6

      - name: Instalar dependências do backend
        run: npm install
        
      - name: Rodar Teste de Carga k6
        run: npm run k6-perf
