name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Testes Unitários, Integração, Infraestrutura (Jest) e Build
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./backend

    steps:
      - uses: actions/checkout@v4

      - name: Configurar Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Instalar dependências do backend
        run: npm install

      - name: Rodar Testes Jest
        run: npm test

  performance-tests: 
    name: Teste de Performance (K6)
    needs: test 
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./backend

    steps:
      - uses: actions/checkout@v4
      
      - name: Configurar Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Instalar K6 no Runner
        run: |
          curl -sL https://github.com/grafana/k6/releases/download/v0.49.0/k6-v0.49.0-linux-amd64.tar.gz -o k6.tar.gz
          
          tar -xzf k6.tar.gz
          
          sudo mv k6-v0.49.0-linux-amd64/k6 /usr/local/bin/k6
          
          k6 version

      - name: Instalar dependências do backend (Node.js)
        run: npm install
        
      - name: Rodar Teste de Carga k6
        run: k6 run ./tests/performance/load-test.js
