name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Testes Unitários, Integração, Infraestrutura (Jest) e Build
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./backend

    steps:
      - uses: actions/checkout@v4

      - name: Configurar Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Instalar dependências do backend
        run: npm install

      - name: Rodar Testes Jest
        run: npm test
  
  security-tests:
    name: Testes de Segurança (npm audit/Snyk)
    needs: test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - uses: actions/checkout@v4
      - name: Configurar Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Instalar dependências
        run: npm install

      - name: Rodar npm audit (Nível Moderado)
        run: npm audit --audit-level=moderate
        
      - name: Instalar Snyk CLI
        run: npm install -g snyk
   
      - name: Snyk Security Scan
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: snyk test --file=backend/package.json --dev --exclude-vulns=SNYK-JS-INFLIGHT-6095116
          
  performance-tests: 
    name: Teste de Performance K6
    needs: test 
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./backend

    steps:
      - uses: actions/checkout@v4
      
      - name: Configurar Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Instalar K6 no Runner
        run: |
          curl -sL https://github.com/grafana/k6/releases/download/v0.49.0/k6-v0.49.0-linux-amd64.tar.gz -o k6.tar.gz
          
          tar -xzf k6.tar.gz
          
          sudo mv k6-v0.49.0-linux-amd64/k6 /usr/local/bin/k6
          
          k6 version

      - name: Instalar dependências do backend (Node.js)
        run: npm install
        
      - name: Rodar Teste de Carga k6
        run: k6 run ./tests/performance/load-test.js

  monitoring-checks:
    name: Verificação de Monitoramento (Sentry)
    needs: [test, security-tests, performance-tests] 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Check SENTRY_DSN Configuration 
        run: |
          if [ -z "${{ secrets.SENTRY_DSN }}" ]; then
            echo "ERRO: Variável SENTRY_DSN não está configurada no GitHub Secrets."
            echo "A integração com Sentry para monitoramento de erros em produção está incompleta."
            exit 1
          fi
          echo "SENTRY_DSN OK! O monitoramento de erros está pronto para uso na aplicação!"