name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Testes Unitários, Integração, Infraestrutura (Jest) e Build
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./backend

    steps:
      - uses: actions/checkout@v4

      - name: Configurar Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Instalar dependências do backend
        run: npm install

      - name: Rodar Testes Jest
        run: npm test

  performance-tests: 
    name: Teste de Performance (k6)
    needs: test 
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./backend

    steps:
      - uses: actions/checkout@v4
      
      - name: Configurar Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Instalar k6 no Runner (MÉTODO CURL + APT - CORREÇÃO FINAL)
        run: |
          sudo apt-get update
          sudo apt-get install -y curl apt-transport-https
          
          curl -s https://key.k6.io/gpg.key | gpg --dearmor | sudo tee /usr/share/keyrings/k6-archive-keyring.gpg >/dev/null
          
          echo "deb [signed-by=/usr/share/keyrings/k6-archive-keyring.gpg] https://dl.k6.io/deb stable main" | sudo tee /etc/apt/sources.list.d/k6.list
          
          sudo apt-get update
          sudo apt-get install k6 -y

      - name: Instalar dependências do backend (Node.js)
        run: npm install
        
      - name: Rodar Teste de Carga k6
        run: npm run k6-perf
